data/p/2021-05-12-changelog.mdx, data/p/2021-05-21-changelog.mdx, data/p/2021-06-05-changelog.mdx, data/p/2021-06-19-changelog.mdx, data/p/2021-06-29-changelog-template copy.mdx, data/p/2021-07-01-changelog.mdx, package.json, pages/index.js, pages/p.js, yarn.lock
- created a changelog tag,
- prevent the home from showing post with the changelog tag,
- created a changelog template in mdx
=> created a change log

README.md, imageScript.js, package.json, yarn.lock
The script takes an array of images in the top section with path and gives this output: 
```
<Image alt={productivity} src={imgSrc} className="object-cover object-center md:h-36 lg:h-48" width={1288} height={858} />
<Image alt={createappDO} src={imgSrc} className="object-cover object-center md:h-36 lg:h-48" width={3364} height={1648} />
```
=> image size script

components/ScrollTopAndComment.js, package.json, yarn.lock
=> share buttons blog

data/p/2023-01-31-changelog.mdx, data/p/2023-03-23-changelog.mdx
J'ai fais simple comme ça m'a déjà pris pas mal de temps, j'ai juste mis le contenu
=> changelogs

components/CTABanner/addToSlack.js, components/CTABanner/templateBanner.js, data/p/developer-experience-survey-template.mdx
=> Call to action for DX

data/p/2023-07-01-changelog.mdx
C'est tellement pratique ce workflow de changelog avec GPT
=>  june changelog

data/p/part-3-github-pull-request-template.mdx, data/p/template.mdx
Je trouvais l'ancienne intro un peu brutale, j'espère attirer plus de gens ou au moins avoir une meilleur brand awareness comme ça
=> Improve pr template article

data/p/best-3-github-pull-request-microsoft-teams-integrations.mdx
=> improve teams article and workflow

components/topBanner/index.js
=> Chromelaunch

data/p/accelerate-four-key-devops-metrics.mdx, pages/index.js
- J'ai updaté un article du blog comme je t'ai dis dans le channel marketing
- J'ai décidé de trier la home page par last mod, je me dis que ça peut créer de l'internal linking pour google et lui mettre en avant qu'on a vraiment updater l'article? et en plus ça pourrait nous faire gagner quelques clicks dessus qui sait..
=> update axolo blog

data/p/14-best-practices-for-software-development.fr.mdx, data/p/7-key-management-takeaways-from-david-heinemeier-hansson.fr.mdx
=> article fr 04 09

layouts/ListLayout.js, pages/index.js
j'ai ajouté les images et créé un infinite scroll sur la page p
=> Page p update

data/p/2024-03-01-changelog.mdx, data/p/2024-07-01-changelog.mdx
=> changelog july

pages/_app.js
=> gtag blog'

components/Footer.js, components/footerAxolo/buildNavigation.js, components/footerAxolo/footerLinks.js, components/footerAxolo/index.js
suite à une demande de netrocket
=> added axolo footer to blog

components/SEO.js, components/footerAxolo/buildNavigation.js, data/headerNavLinks.js, layouts/ListLayout.js, layouts/PostLayout.js, locales/en/common.json, locales/fr/common.json, next.config.js, pages/index.js, pages/tags/[tag].js
je veux bien que tu testes la pagination et la redirection /p vers / please au cas ou!
=> Canonical blog url & pagination on home page

robot.txt
j'ouvre une PR pour que tu check que c'est ok et je confirme avec l'agence avant de merge, je leur laisse un com
=> disallow > tags

components/SEO.js, pages/p.js
=> fix seo meta title blog

data/p/slack-gitlab-merge-requests-integrations.mdx
=> refonte: Top 6 Slack GitLab merge request integrations

data/p/pull-request-vs-merge-request.mdx
preview https://blog-axolo-git-pullvsmerge-axolo-team.vercel.app/blog/p/pull-request-vs-merge-request
=> pull vs merge 

.gitignore, data/p/git-commit-messages-best-practices-examples.mdx
=> Axo 1964 - git commit msg update

components/SEO.js
=> locale main blog page

components/SEO.js
=> modified seo js file

components/Link.js, components/Tag.js, lib/utils/formatDate.js, pages/index.js
Some updates because the blog was throwing errors
=> blog update
